import { type Metadata } from "next";
import { Geist } from "next/font/google";
import { PreferencesProvider } from "~/components/providers/preferences-provider";
import "~/styles/globals.css";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${geist.variable}`}>
      <body className="bg-black">
        <PreferencesProvider>{children}</PreferencesProvider>
      </body>
    </html>
  );
}
